config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'auth/:provider/callback' => 'auth#callback'
  get 'auth/logout' => 'auth#logout'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def callback
    provider_user = request.env['omniauth.auth']
    render json: provider_user
    # user = User.find_or_create_by(provider_id: provider_user['uid'], provider: params[:provider]) do |u|

    #   u.provider_hash = provider_user['credentials']['token']
    #   u.name = provider_user['info']['name']
    #   u.email = provider_user['info']['email']

    # end

    # session[:user_id] = user.id
    # redirect_to root_path

  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OhAuthExample</title>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/main/index.html.erb
<h1>Home</h1>

<%= link_to "Login with Facebook", "/auth/facebook", class: "btn btn-primary" %>

<%= link_to "Logout", auth_logout_path %>

<div class="well">
  Current User:
  <%= @current_user.inspect %>
</div>